load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "sharable",
    srcs = ["Sharable.java"],
    main_class = "src/com/thrillio/partners/Sharable.java",
    visibility = ["//src/com/thrillio/entities:__pkg__","//src/com/thrillio/dao:__pkg__","//src/com/thrillio/managers:__pkg__"],
)
